### PR TITLE
domain: add google adsense and analytics tracking

### PR DESCRIPTION
**Pull request by KhasMek**
This module will check the specified domain for google
  tracking codes and then use the spyonweb api to check
  for other sites using the same code(s).

  Full credit for this idea and base code goes to Justin Seitz
  (Twitter - @jms_dot_py) of Automating OSINT. I just adopted
  and modified the code to work within datasploit.

  Original article -
    http://www.automatingosint.com/blog/2017/07/osint-website-connections-tracking-codes/

  Original code -
    https://github.com/automatingosint/osint_public/blob/master/trackingcodes/website_connections.py

### CODE REVIEW

**Review by upgoingstar — COMMENTED** [review]
Can you also send in a quick .md formatted documentation for generating this API key (just like steps mentioned in documentation https://datasploit.github.io/datasploit/apiGeneration/

**Comment by upgoingstar** [comment]
I cannot find other domain;s information. Referred to Justin's blog too, but can't figure it out. Looks like this needs a little bit of more logic changes. I am merging this into the code but will disable it, until we get a working piece of code.

**Comment by KhasMek** [comment]
What do you mean by "find other domian's information"?

**Comment by upgoingstar** [comment]
I passed multiple domains, but for all of them, it either returned 'No tracking code found' or it returned the tracking code. It, however, did not return the domains which are using the same Tracking code. 

Am I missing out something? or the code is not supposed to do that at all?

**Comment by KhasMek** [comment]
They won't always be used across multiple sites (in fact I consider it good practice to not). Here is an example site that does use the same code across multiple sites though.

```
➜  datasploit git:(googletracking) ✗ python domain/domain_googletracking.py androidpolice.com

[+] Checking for Google tracking codes.

pub-5262833430322012:
	androidpolice.com
	www.androidpolice.com
UA-6275685:
	androidpolice.com
	beerpla.net
	www.androidpolice.com
	www.apkmirror.com
pub-8776668743582988:
	androidpolice.com
	www.apkmirror.com
	www.mikekoepke.com

Tracking Codes:
	pub-5262833430322012
	UA-6275685
	pub-8776668743582988
➜  datasploit git:(googletracking) ✗ 
```

**Comment by upgoingstar** [comment]
Agreed. I tried on a bunch of sites which should have returned related sites (but then checked at the API and API itself is not returning the same), so I got confused. 

Thanks for writing this nice module. Cheers.

**Pull request merged**
